# Generated by Django 5.1.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isubscribe_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='is_tool_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='tool_args',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='tool_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='tool_result',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
